config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v2 do
      get 'order_locations/index'
    end
  end

  namespace :api do
    namespace :v2 do
      resources :sessions, :reservations, :device_tokens, :materials, :material_orders, :tables, :dishes, :users, :order_locations
    end
  end

  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine => '/docs'
  
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do 
    
    root 'home#index'
    
    resources :home, :sessions, :privacy
    
    get '/dang-xuat' => 'sessions#destroy', :as => 'dang-xuat'
    get '/dang-nhap' => 'sessions#new', :as => 'dang-nhap'
    
    namespace :admin do
      resources :dashboard, :roles, :users, :reservation_statuses, :languages, :categories, :materials, 
      :material_orders, :tables, :dishes, :request_statuses, :role_requests, :order_locations
      
      resources :locations do 
        collection do
          get '/:id/assignOwner' => :assignOwnerView, as: "assignOwner"
          post '/:id/assignOwner' => :assignOwner, as: "assignOwnerP"
        end
      end
      
      resources :reservations do
        collection do
          get 'getListCurrentData'
          post '/:id/cancelReservation' => :cancelReservation, as: "cancelReservation"
          post '/:id/confirmReservationOK' => :confirmReservationOK, as: "confirmReservationOK"
          post '/:id/confirmReservationNoK' => :confirmReservationNoK, as: "confirmReservationNoK"
        end
      end
      
      resources :restaurants do
        collection do
          get '/:id/makeConnection' => :makeConnection, as: "makeConnection"
        end
      end
    end 
    
    
    
  end
  
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")

  
  

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :location_categories
    has_many :locations, through: :location_categories

end

app/models/connection.rb
class Connection < ApplicationRecord
    has_many :locations
end

app/models/device_token.rb
class DeviceToken < ApplicationRecord
end

app/models/dish.rb
class Dish < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
    has_many :locations
end

app/models/location.rb
class Location < ApplicationRecord
    attr_accessor :name, :description, :language_id, :address
    
    has_many :location_translations
    belongs_to :language
    belongs_to :user
    has_many :location_categories, dependent: :destroy
    has_many :categories, through: :location_categories
    has_many :reservations
    has_many :connections
    
end

app/models/material.rb
class Material < ApplicationRecord
    has_many :material_orders
    belongs_to :order_location
end

app/models/material_order.rb
class MaterialOrder < ApplicationRecord
    belongs_to :material
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_dish.rb
class OrderDish < ApplicationRecord
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
end

app/models/package.rb
class Package < ApplicationRecord
end

app/models/pto_request.rb
class PtoRequest < ApplicationRecord
end

app/models/receiver.rb
class Receiver < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :reservation_status
    belongs_to :location
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users
    has_many :role_requests
end

app/models/role_request.rb
class RoleRequest < ApplicationRecord
    belongs_to :role
    belongs_to :user
end

app/models/table.rb
class Table < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    belongs_to :role
    has_many :role_requests
    
    before_create :encrypted_password
    
    def has_password?(submitted_password)
        encrypt_password == encrypt(submitted_password)
    end
    
    def self.authenticate(name, submitted_password)
        user = User.find_by(name: name)
        return nil if user.nil?
        return user if user.has_password?(submitted_password)
    end
    
    private
        def encrypted_password
            #generate a unique salt if it is a new user
            self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
            
            #encrypt the password and store that in the ecrypted_password field
            self.encrypt_password = encrypt(password)
        end
        
        def encrypt(pass)
            Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
        end
end

app/models/user_receiver.rb
class UserReceiver < ApplicationRecord
end

app/controllers/admin/materials_controller.rb
class Admin::MaterialsController < Admin::ApplicationController
  before_filter :verify_logged
  
  def new
    @material = Material.new
  end

  def create
    @material = Material.new(material_params)
    @material.created_by = current_user.name
    @material.updated_by = current_user.name
    @material.delete_flag = 0
    
    if @material.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to admin_materials_path
    else
      render 'new'
    end
  end

  def index
    @materials = Material.where(delete_flag: 0).all
  end

  def show
  end

  def edit
    @material = Material.find(params[:id])
  end

  def update
    @material = Material.find(params[:id])
    @material.name = params[:material][:name]
    @material.order_location_id = params[:material][:order_location_id]
    @material.description = params[:material][:description]
    @material.description = params[:material][:unit]
    @material.updated_by = current_user.name
    
    if @material.save
      flash[:success] = 'Cập nhật thành công'
      redirect_to admin_materials_path
    else
      render 'edit'
    end
  end

  def destroy
  end
  
  private
    def material_params
      params.require(:material).permit(:name, :order_location_id, :description, :unit, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/api/v2/materials_controller.rb
class Api::V2::MaterialsController < Api::V2::ApplicationController
  before_action :verify_authorzation
  
  def index
    if params[:location].nil?
      @materials = Material.where(delete_flag: 0)
    else
      @materials = Material.where(order_location_id: params[:location], delete_flag: 0)
    end
    
    render json: {
           "status": "OK",
           "code": "200",
           "messages":"Danh sách Hàng",
           "result": @materials.as_json(except: [:delete_flag],
           include: {
            order_location: {
              except: [:delete_flag, :created_at, :updated_at, :created_by, :updated_by]
            }
         })
     }
  end
end

app/helpers/admin/materials_helper.rb
module Admin::MaterialsHelper
end

app/helpers/api/v2/materials_helper.rb
module Api::V2::MaterialsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/materials/create.html.erb
<h1>Admin::Materials#create</h1>
<p>Find me in app/views/admin/materials/create.html.erb</p>

app/views/admin/materials/destroy.html.erb
<h1>Admin::Materials#destroy</h1>
<p>Find me in app/views/admin/materials/destroy.html.erb</p>

app/views/admin/materials/edit.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= t("laluna.menu.list_material_management") %><small></small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <%= form_for [:admin, @material], :html => {:class => 'form-horizontal form-label-left'} do |f| %>
              </p>
              <span class="section"><%= t("laluna.label.add_material") %></span>

              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name"><%= t("laluna.label.material_name") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :name, class:'form-control col-md-7 col-xs-12', 'data-validate-left-range' =>'5', 'data-validate-words' =>'1', placeholder:'', 'required' => 'required' %>
                </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description"><%= t("laluna.label.unit") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :unit, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
               <div class="item form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="role"><%= t("laluna.label.location_name") %> <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                      <%= f.select :order_location_id, OrderLocation.where(delete_flag: 0).all.collect {|x| [x.name, x.id]},{:include_blank => t("laluna.label.select_location")}, class:'form-control' %>
                  </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description"><%= t("laluna.label.description") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :description, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-6 col-md-offset-3">
                  <%= link_to t("laluna.label.cancel"), new_admin_material_path, class:'btn btn-primary' %>
                  <%= f.submit t("laluna.label.confirm"), class:'btn btn-success' %>
                </div>
              </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/materials/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= t("laluna.menu.list_material") %> <small></small></h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="<%= t("laluna.menu.search_for")%>">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <%= link_to t("laluna.label.add_new"), new_admin_material_path, class: "btn btn-success pull-right" %>
          
          <div class="x_content">
             
            <div class="table-responsive">
              <table class="table table-striped jambo_table bulk_action">
                <thead>
                  <tr class="headings">
                    <th>
                      <input type="checkbox" id="check-all" class="flat">
                    </th>
                    <th class="column-title">ID </th>
                    <th class="column-title"><%= t("laluna.label.material_name")%></th>
                    <th class="column-title"><%= t("laluna.label.unit") %></th>
                    <th class="column-title"><%= t("laluna.label.location_name") %></th>
                    <th class="column-title"><%= t("laluna.label.description") %></th>
                    <th class="column-title"><%= t("laluna.label.created_date") %></th>
                    <th class="column-title"><%= t("laluna.label.updated_date") %></th>
                    <th class="column-title no-link last"><span class="nobr"><%= t("laluna.label.action") %></span>
                    </th>
                    
                  </tr>
                </thead>

                <tbody>
                  <% @materials.each do |f| %>
                    <tr class="even pointer">
                      <td class="a-center ">
                        <input type="checkbox" class="flat" name="table_records">
                      </td>
                      <td class=" "><%= f.id %></td>
                      <td class=" "><%= f.name %> </td>
                      <td class=" "><%= f.unit %> </td>
                      <% if f.order_location.nil? %>
                      <td class=" "></td>
                      <% else %>
                      <td class=" "><%= f.order_location.name %></td>
                      <% end %>
                      <td class=" "><%= f.description %></td>
                      <td class=" "><%= f.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
                      <td class=" "><%= f.created_at.to_time.strftime('%B %e at %l:%M %p') %> </td>
                      <td class=" "><%= link_to t("laluna.label.edit"), edit_admin_material_path(f), class:'btn btn-primary' %> 
                        <%= link_to t("laluna.label.delete"), admin_material_path(f), class:'btn btn-danger', method: :delete, data: {confirm: t("laluna.messages.confirm_delete")} %>
                      </td>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/materials/new.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= t("laluna.menu.list_material_management") %><small></small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <%= form_for [:admin, @material], :html => {:class => 'form-horizontal form-label-left'} do |f| %>
              </p>
              <span class="section"><%= t("laluna.label.add_material") %></span>

              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name"><%= t("laluna.label.material_name") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :name, class:'form-control col-md-7 col-xs-12', 'data-validate-left-range' =>'5', 'data-validate-words' =>'1', placeholder:'', 'required' => 'required' %>
                </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description"><%= t("laluna.label.unit") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :unit, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
               <div class="item form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="role"><%= t("laluna.label.location_name") %> <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                      <%= f.select :order_location_id, OrderLocation.where(delete_flag: 0).all.collect {|x| [x.name, x.id]},{:include_blank => t("laluna.label.select_location")}, class:'form-control' %>
                  </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description"><%= t("laluna.label.description") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :description, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-6 col-md-offset-3">
                  <%= link_to t("laluna.label.cancel"), new_admin_material_path, class:'btn btn-primary' %>
                  <%= f.submit t("laluna.label.confirm"), class:'btn btn-success' %>
                </div>
              </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/materials/show.html.erb
<h1>Admin::Materials#show</h1>
<p>Find me in app/views/admin/materials/show.html.erb</p>

app/views/admin/materials/update.html.erb
<h1>Admin::Materials#update</h1>
<p>Find me in app/views/admin/materials/update.html.erb</p>