config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v2 do
      get 'order_locations/index'
    end
  end

  namespace :api do
    namespace :v2 do
      resources :sessions, :reservations, :device_tokens, :materials, :material_orders, :tables, :dishes, :users, :order_locations
    end
  end

  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine => '/docs'
  
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do 
    
    root 'home#index'
    
    resources :home, :sessions, :privacy
    
    get '/dang-xuat' => 'sessions#destroy', :as => 'dang-xuat'
    get '/dang-nhap' => 'sessions#new', :as => 'dang-nhap'
    
    namespace :admin do
      resources :dashboard, :roles, :users, :reservation_statuses, :languages, :categories, :materials, 
      :material_orders, :tables, :dishes, :request_statuses, :role_requests, :order_locations
      
      resources :locations do 
        collection do
          get '/:id/assignOwner' => :assignOwnerView, as: "assignOwner"
          post '/:id/assignOwner' => :assignOwner, as: "assignOwnerP"
        end
      end
      
      resources :reservations do
        collection do
          get 'getListCurrentData'
          post '/:id/cancelReservation' => :cancelReservation, as: "cancelReservation"
          post '/:id/confirmReservationOK' => :confirmReservationOK, as: "confirmReservationOK"
          post '/:id/confirmReservationNoK' => :confirmReservationNoK, as: "confirmReservationNoK"
        end
      end
      
      resources :restaurants do
        collection do
          get '/:id/makeConnection' => :makeConnection, as: "makeConnection"
        end
      end
    end 
    
    
    
  end
  
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")

  
  

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :location_categories
    has_many :locations, through: :location_categories

end

app/models/connection.rb
class Connection < ApplicationRecord
    has_many :locations
end

app/models/device_token.rb
class DeviceToken < ApplicationRecord
end

app/models/dish.rb
class Dish < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
    has_many :locations
end

app/models/location.rb
class Location < ApplicationRecord
    attr_accessor :name, :description, :language_id, :address
    
    has_many :location_translations
    belongs_to :language
    belongs_to :user
    has_many :location_categories, dependent: :destroy
    has_many :categories, through: :location_categories
    has_many :reservations
    has_many :connections
    
end

app/models/material.rb
class Material < ApplicationRecord
    has_many :material_orders
    belongs_to :order_location
end

app/models/material_order.rb
class MaterialOrder < ApplicationRecord
    belongs_to :material
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_dish.rb
class OrderDish < ApplicationRecord
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
end

app/models/package.rb
class Package < ApplicationRecord
end

app/models/pto_request.rb
class PtoRequest < ApplicationRecord
end

app/models/receiver.rb
class Receiver < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :reservation_status
    belongs_to :location
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users
    has_many :role_requests
end

app/models/role_request.rb
class RoleRequest < ApplicationRecord
    belongs_to :role
    belongs_to :user
end

app/models/table.rb
class Table < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    belongs_to :role
    has_many :role_requests
    
    before_create :encrypted_password
    
    def has_password?(submitted_password)
        encrypt_password == encrypt(submitted_password)
    end
    
    def self.authenticate(name, submitted_password)
        user = User.find_by(name: name)
        return nil if user.nil?
        return user if user.has_password?(submitted_password)
    end
    
    private
        def encrypted_password
            #generate a unique salt if it is a new user
            self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
            
            #encrypt the password and store that in the ecrypted_password field
            self.encrypt_password = encrypt(password)
        end
        
        def encrypt(pass)
            Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
        end
end

app/models/user_receiver.rb
class UserReceiver < ApplicationRecord
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::ApplicationController
  before_filter :verify_logged
  
  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.created_by = "yle"
    @location.updated_by = "yle"
    @location.delete_flag = 0
    
    if @location.save
      @location_translation = LocationTranslation.new
      @location_translation.location_id = @location.id
      @location_translation.language_id = (params["location"]["language_id"]).to_i
      @location_translation.name = params["location"]["name"]
      @location_translation.description = params["location"]["description"]
      @location_translation.address = params["location"]["address"]
      @location_translation.created_by = @location.created_by
      @location_translation.created_at = @location.created_at
      @location_translation.updated_by = @location.updated_by
      @location_translation.updated_at = @location.updated_at
      @location_translation.delete_flag = 0
      
      if @location_translation.save
        redirect_to admin_locations_path
      else
        render 'new'
      end
    else
      render 'new'
    end
    
  end

  def edit
  end

  def update
  end

  def index
    @lang = Language.find_by("name": params[:locale])
    @locations = Location.joins(:location_translations).where(['location_translations.language_id = ?', @lang.id])
  end

  def show
  end

  def destroy
  end
  
  def assignOwnerView
    @location = Location.new
  end
  
  def assignOwner
    @location = Location.find(params[:id])
    
    if @location.update(user_id: params["location"]["user_id"].to_i) 
      redirect_to admin_locations_path
    else
      redirect_to admin_locations_path
    end
  end
  
  
  private
    def location_params
      params.require(:location).permit(
        :latitude, 
        :longitude, 
        :user_id, 
        :phone, 
        :created_by, 
        :updated_by, 
        :delete_flag,
        category_ids: [])
    end
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/locations/assignOwnerView.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= t("laluna.label.assign_owner") %><small></small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <%= form_for [:admin, @location], :url => assignOwnerP_admin_locations_path, :html => {:class => 'form-horizontal form-label-left'} do |f| %>
              </p>
              <span class="section"><%= t("laluna.label.add_user") %></span>

              
              <div class="item form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="role"><%= t("laluna.label.user_name") %> <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                      <%= f.select :user_id, User.where(delete_flag: 0).all.collect {|x| [x.name, x.id]},{:include_blank => t("laluna.label.select_owner")}, class:'form-control' %>
                  </div>
              </div>
              
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-6 col-md-offset-3">
                  <%= link_to t("laluna.label.cancel"), new_admin_role_path, class:'btn btn-primary' %>
                  <%= f.submit t("laluna.label.confirm"), class:'btn btn-success' %>
                </div>
              </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/locations/create.html.erb
<h1>Admin::Locations#create</h1>
<p>Find me in app/views/admin/locations/create.html.erb</p>

app/views/admin/locations/destroy.html.erb
<h1>Admin::Locations#destroy</h1>
<p>Find me in app/views/admin/locations/destroy.html.erb</p>

app/views/admin/locations/edit.html.erb
<h1>Admin::Locations#edit</h1>
<p>Find me in app/views/admin/locations/edit.html.erb</p>

app/views/admin/locations/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= t("laluna.label.list_location") %> <small></small></h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="<%= t("laluna.menu.search_for")%>">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <%= link_to t("laluna.label.add_new"), new_admin_location_path, class: "btn btn-success pull-right" %>
          
          <div class="x_content">
             
            <div class="table-responsive">
              <table class="table table-striped jambo_table bulk_action">
                <thead>
                  <tr class="headings">
                    <th>
                      <input type="checkbox" id="check-all" class="flat">
                    </th>
                    <th class="column-title">ID </th>
                    <th class="column-title"><%= t("laluna.label.location_name")%></th>
                    <th class="column-title"><%= t("laluna.label.address") %></th>
                    <th class="column-title"><%= t("laluna.label.created_date") %></th>
                    <th class="column-title"><%= t("laluna.label.updated_date") %></th>
                    <th class="column-title no-link last"><span class="nobr"><%= t("laluna.label.action") %></span>
                    </th>
                    
                  </tr>
                </thead>

                <tbody>
                  <% @locations.each do |f| %>
                    <tr class="even pointer">
                      <td class="a-center ">
                        <input type="checkbox" class="flat" name="table_records">
                      </td>
                      <td class=" "><%= f.id %></td>
                      <td class=" "><%= f.location_translations[0].name %> </td>
                      <td class=" "><%= f.location_translations[0].address %></td>
                      <td class=" "><%= f.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
                      <td class=" "><%= f.created_at.to_time.strftime('%B %e at %l:%M %p') %> </td>
                      <td class=" ">
                        <% if f.user_id == 0 %>
                          <%= link_to t("laluna.label.assign_owner"), assignOwner_admin_locations_path(f), class:'btn btn-info' %> 
                        <% else %>
                          <%= link_to t("laluna.label.change_owner"), "#", class:'btn btn-danger' %> 
                        <% end %>
                        <%= link_to t("laluna.label.edit"), edit_admin_role_path(f), class:'btn btn-primary' %> 
                        <%= link_to t("laluna.label.delete"), admin_role_path(f), class:'btn btn-danger', method: :delete, data: {confirm: t("laluna.messages.confirm_delete")} %>
                      </td>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/locations/new.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= t("laluna.menu.location_management") %><small></small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <%= form_for [:admin, @location], :html => {:class => 'form-horizontal form-label-left'} do |f| %>
              </p>
              <span class="section"><%= t("laluna.label.add_location") %></span>

              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name"><%= t("laluna.select_language") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                      <%= f.select :language_id, Language.where(delete_flag: 0).all.collect {|x| [x.name, x.id]},{:include_blank => t("laluna.select_language")}, class:'form-control' %>
                  </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description"><%= t("laluna.label.location_name") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :name, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description"><%= t("laluna.label.location_address") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :address, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description"><%= t("laluna.label.location_phone") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :phone, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description"><%= t("laluna.label.location_latitude") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :latitude, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description"><%= t("laluna.label.location_longitude") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :longitude, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description"><%= t("laluna.label.category_name") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                      <%= f.select :category_ids, Category.where(delete_flag: 0).all.collect {|x| [x.name, x.id]},{:include_blank => t("laluna.select_category")}, class:'form-control js-example-basic-multiple', "multiple" => "multiple", required: 'require'  %>
                  </div>
              </div>
              <div class="item form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description"><%= t("laluna.label.location_desc") %><span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.cktext_area :description, class: 'form-control col-md-7 col-xs-12', rows: '10'%>
                </div>
              </div>
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-6 col-md-offset-3">
                  <%= link_to t("laluna.label.cancel"), new_admin_role_path, class:'btn btn-primary' %>
                  <%= f.submit t("laluna.label.confirm"), class:'btn btn-success' %>
                </div>
              </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/locations/show.html.erb
<h1>Admin::Locations#show</h1>
<p>Find me in app/views/admin/locations/show.html.erb</p>

app/views/admin/locations/update.html.erb
<h1>Admin::Locations#update</h1>
<p>Find me in app/views/admin/locations/update.html.erb</p>