config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v2 do
      get 'order_locations/index'
    end
  end

  namespace :api do
    namespace :v2 do
      resources :sessions, :reservations, :device_tokens, :materials, :material_orders, :tables, :dishes, :users, :order_locations
    end
  end

  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine => '/docs'
  
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do 
    
    root 'home#index'
    
    resources :home, :sessions, :privacy
    
    get '/dang-xuat' => 'sessions#destroy', :as => 'dang-xuat'
    get '/dang-nhap' => 'sessions#new', :as => 'dang-nhap'
    
    namespace :admin do
      resources :dashboard, :roles, :users, :reservation_statuses, :languages, :categories, :materials, 
      :material_orders, :tables, :dishes, :request_statuses, :role_requests, :order_locations
      
      resources :locations do 
        collection do
          get '/:id/assignOwner' => :assignOwnerView, as: "assignOwner"
          post '/:id/assignOwner' => :assignOwner, as: "assignOwnerP"
        end
      end
      
      resources :reservations do
        collection do
          get 'getListCurrentData'
          post '/:id/cancelReservation' => :cancelReservation, as: "cancelReservation"
          post '/:id/confirmReservationOK' => :confirmReservationOK, as: "confirmReservationOK"
          post '/:id/confirmReservationNoK' => :confirmReservationNoK, as: "confirmReservationNoK"
        end
      end
      
      resources :restaurants do
        collection do
          get '/:id/makeConnection' => :makeConnection, as: "makeConnection"
        end
      end
    end 
    
    
    
  end
  
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")

  
  

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :location_categories
    has_many :locations, through: :location_categories

end

app/models/connection.rb
class Connection < ApplicationRecord
    has_many :locations
end

app/models/device_token.rb
class DeviceToken < ApplicationRecord
end

app/models/dish.rb
class Dish < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
    has_many :locations
end

app/models/location.rb
class Location < ApplicationRecord
    attr_accessor :name, :description, :language_id, :address
    
    has_many :location_translations
    belongs_to :language
    belongs_to :user
    has_many :location_categories, dependent: :destroy
    has_many :categories, through: :location_categories
    has_many :reservations
    has_many :connections
    
end

app/models/material.rb
class Material < ApplicationRecord
    has_many :material_orders
    belongs_to :order_location
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_dish.rb
class OrderDish < ApplicationRecord
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
end

app/models/package.rb
class Package < ApplicationRecord
end

app/models/pto_request.rb
class PtoRequest < ApplicationRecord
end

app/models/receiver.rb
class Receiver < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :reservation_status
    belongs_to :location
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users
    has_many :role_requests
end

app/models/role_request.rb
class RoleRequest < ApplicationRecord
    belongs_to :role
    belongs_to :user
end

app/models/table.rb
class Table < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    belongs_to :role
    has_many :role_requests
    
    before_create :encrypted_password
    
    def has_password?(submitted_password)
        encrypt_password == encrypt(submitted_password)
    end
    
    def self.authenticate(name, submitted_password)
        user = User.find_by(name: name)
        return nil if user.nil?
        return user if user.has_password?(submitted_password)
    end
    
    private
        def encrypted_password
            #generate a unique salt if it is a new user
            self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
            
            #encrypt the password and store that in the ecrypted_password field
            self.encrypt_password = encrypt(password)
        end
        
        def encrypt(pass)
            Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
        end
end

app/models/user_receiver.rb
class UserReceiver < ApplicationRecord
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/admin/admin.html.erb
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Laluna Palace | <%= t "laluna.administrator_title" %></title>  
  <%= stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag Ckeditor.cdn_url %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        
        <%= render 'partials/admin/menu' %>

        <%= render 'partials/admin/topnavigation' %>
        
        <!-- page content -->
        <%= yield %>
        <!-- /page content -->
        <%= render 'partials/admin/footer' %>
      </div>
    </div>
  </body>
</body> 
</html>

app/views/partials/admin/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    A Product of <a href="https://lalunapalace.com">LalunaPalace</a> © 2017
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->

app/views/partials/admin/_menu.html.erb
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="#" class="site_title"><i class="fa fa-moon-o"></i> <span>Laluna Palace</span></a>
    </div>
    
    <div class="clearfix"></div>
    
    <!-- menu profile quick info -->
    <div class="profile clearfix">
      <div class="profile_pic">
        <%= image_tag("img.jpg", class: "img-circle profile_img", alt: "...") %>
      </div>
      <div class="profile_info">
        <span><%= t("laluna.welcome") %>,</span>
        <h2><%= current_user.name %></h2>
      </div>
    </div>
    <!-- /menu profile quick info -->
    
    <br />
    
    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <h3><%= t("laluna.menu.general") %></h3>
        <ul class="nav side-menu">
          <li><a><i class="fa fa-home"></i> <%= t("laluna.menu.general") %> <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li>
                <%= link_to "Dashboard", admin_dashboard_index_path %>
              </li>
            </ul>
          </li>
          <% if is_admin? %>
          <li><a><i class="fa fa-desktop"></i> <%= t("laluna.menu.information") %><span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><%= link_to t("laluna.menu.user_management"), admin_users_path %></li>
              <li><%= link_to t("laluna.menu.role_management"), admin_roles_path %></li>
              <li><%= link_to t("laluna.menu.reservation_status_management"), admin_reservation_statuses_path %></li>
              <li><%= link_to t("laluna.menu.language_management"), admin_languages_path %></li>
              <li><%= link_to t("laluna.menu.category_management"), admin_categories_path %></li>
              <li><%= link_to t("laluna.menu.request_status_manager"), admin_request_statuses_path %></li>
            </ul>
          </li>
          
          <li><a><i class="fa fa-desktop"></i> <%= t("laluna.menu.location_management") %><span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><%= link_to t("laluna.label.list_location"), admin_locations_path %></li>
            </ul>
          </li>
          <% end %>
          <li><a><i class="fa fa-coffee"></i> <%= t("laluna.menu.restaurant_management") %><span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><%= link_to t("laluna.menu.list_restaurant"), admin_restaurants_path %></li>
              <li><%= link_to t("laluna.menu.reservation_management"), admin_reservations_path %></li>
            </ul>
          </li>
          <% if is_admin? %>
          <li><a><i class="fa fa-shopping-cart"></i> <%= t("laluna.menu.material_management") %><span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><%= link_to t("laluna.menu.list_material"), admin_materials_path %></li>
              <li><%= link_to t("laluna.menu.order_location"), admin_order_locations_path %></li>
              <li><%= link_to t("laluna.menu.material_order"), admin_material_orders_path %></li>
            </ul>
          </li>
          <li><a><i class="fa fa-shopping-cart"></i> <%= t("laluna.menu.laluna_management") %><span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><%= link_to t("laluna.menu.table_management"), admin_tables_path %></li>
              <li><%= link_to t("laluna.menu.dish_management"), admin_dishes_path %></li>
            </ul>
          </li>
          <li><a><i class="fa fa-shopping-cart"></i> <%= t("laluna.menu.request_management") %><span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><%= link_to t("laluna.menu.role_request"), admin_role_requests_path %></li>
              <li><%= link_to t("laluna.menu.pro_request"), "#" %></li>
            </ul>
          </li>
          <li><a><i class="fa fa-bar-chart-o"></i> <%= t("laluna.menu.statistics") %> <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="#"><%= t("laluna.menu.statistics") %></a></li>
            </ul>
          </li>
          <% end %>
          <!--<li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="general_elements.html">General Elements</a></li>
              <li><a href="media_gallery.html">Media Gallery</a></li>
              <li><a href="typography.html">Typography</a></li>
              <li><a href="icons.html">Icons</a></li>
              <li><a href="glyphicons.html">Glyphicons</a></li>
              <li><a href="widgets.html">Widgets</a></li>
              <li><a href="invoice.html">Invoice</a></li>
              <li><a href="inbox.html">Inbox</a></li>
              <li><a href="calendar.html">Calendar</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="tables.html">Tables</a></li>
              <li><a href="tables_dynamic.html">Table Dynamic</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="chartjs.html">Chart JS</a></li>
              <li><a href="chartjs2.html">Chart JS2</a></li>
              <li><a href="morisjs.html">Moris JS</a></li>
              <li><a href="echarts.html">ECharts</a></li>
              <li><a href="other_charts.html">Other Charts</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
              <li><a href="fixed_footer.html">Fixed Footer</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="menu_section">
        <h3>Live On</h3>
        <ul class="nav side-menu">
          <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="e_commerce.html">E-commerce</a></li>
              <li><a href="projects.html">Projects</a></li>
              <li><a href="project_detail.html">Project Detail</a></li>
              <li><a href="contacts.html">Contacts</a></li>
              <li><a href="profile.html">Profile</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="page_403.html">403 Error</a></li>
              <li><a href="page_404.html">404 Error</a></li>
              <li><a href="page_500.html">500 Error</a></li>
              <li><a href="plain_page.html">Plain Page</a></li>
              <li><a href="login.html">Login Page</a></li>
              <li><a href="pricing_tables.html">Pricing Tables</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="#level1_1">Level One</a>
                <li><a>Level One<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li class="sub_menu"><a href="level2.html">Level Two</a>
                    </li>
                    <li><a href="#level2_1">Level Two</a>
                    </li>
                    <li><a href="#level2_2">Level Two</a>
                    </li>
                  </ul>
                </li>
                <li><a href="#level1_2">Level One</a>
                </li>
            </ul>
          </li>                  
          <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>-->
        </ul>
      </div>
    
    </div>
    <!-- /sidebar menu -->
    
    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
      <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
      </a>
      <%= link_to dang_xuat_path do %>
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
      <% end %>
    </div>
    <!-- /menu footer buttons -->
    </div>
</div>

app/views/partials/admin/_notification.html.erb
<% if flash[:success] %>
    <div class="alert alert-success alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <strong><%= flash[:success] %></strong>
    </div>
    <% elsif flash[:error] %>
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
      </button>
      <%= flash[:error] %>
    </div>
<% end %>

app/views/partials/admin/_topnavigation.html.erb
<!-- top navigation -->
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag("img.jpg",alt:"") %>
            <%= current_user.name %>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Profile</a></li>
            <li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li><a href="javascript:;">Help</a></li>
            <li>
              <%= link_to dang_xuat_path do %>
                <%= t("laluna.label.logout")  %><i class="fa fa-sign-out pull-right"></i>
              <% end %>
            </li>
          </ul>
        </li>
        
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= t ("laluna.select_language") %>
            <span class=" fa fa-language"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li>
              <%= link_to "Tiếng Việt", locale: "vi" %> 
            </li>
            <li>
              <%= link_to "English", locale: "en" %> 
            </li>
            <li><a href="javascript:;"><%= t ("laluna.languages.kr") %></a></li>
            <li><a href="javascript:;"><%= t ("laluna.languages.jp") %></a></li>
            <li><a href="javascript:;"><%= t ("laluna.languages.cn") %></a></li>
            
          </ul>
        </li>

        <!--<li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                <span class="image">
                  <%= image_tag("img.jpg", alt: "Profile Image") %>
                </span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image">
                  <%= image_tag("img.jpg", alt: "Profile Image") %>
                </span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><%= image_tag("img.jpg", alt: "Profile Image") %></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><%= image_tag("img.jpg", alt: "Profile Image") %></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>-->
      </ul>
    </nav>
  </div>
</div>
<!-- /top navigation -->